### ISSUE TITLE
Angular 5.x

### ISSUE THREAD

**Issue by inklingsofreality** [abhazelton/animate-on-scroll#9] opened 2017-11-14 15:01 UTC
The library does not compile on Angular 5.x. The workaround is to add the following to tsconfig.json, which I can confirm works:
```
"include": [
    "src/**/*",
    "node_modules/ng2-animate-on-scroll/index.ts",
    "node_modules/ng2-animate-on-scroll/**/*.ts"
  ]
```
The solution is apparently for the module to be pre-compiled before inclusion. 
See https://github.com/angular/angular-cli/issues/8284
for the proper solution.

**Comment by abhazelton** [comment] 2017-11-17 04:12
Thanks @inklingsofreality for pointing this out.  I have removed the source files and published to npm again.  Can you check in your project that this issue is gone?

**Comment by Bidthedog** [comment] 2017-11-22 17:22
@inklingsofreality Is this the error you're getting? I was on 1.06, now upgraded to 1.0.8 and still getting it. Angular 5.0.2

> ERROR in Error: Error encountered resolving symbol values statically. Calling function 'AnimateOnScrollModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in F:/Git/ShadowMosesWebsite/src/ShadowMoses.Web/src/app/app
> 
> .module.ts, resolving symbol AppModule in F:/Git/ShadowMosesWebsite/src/ShadowMoses.Web/src/app/app.module.ts
>     at syntaxError (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
>     at simplifyInContext (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24979:23)
>     at StaticReflector.simplify (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24991:13)
>     at StaticReflector.annotations (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler\bundles\compiler.umd.js:24418:41)
>     at _getNgModuleMetadata (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
>     at _extractLazyRoutesFromStaticModule (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
>     at Object.listLazyRoutesOfModule (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
>     at Function.NgTools_InternalApi_NG_2.listLazyRoutes (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
>     at AotPlugin._getLazyRoutesFromNgtools (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@ngtools\webpack\src\plugin.js:241:66)
>     at _donePromise.Promise.resolve.then.then.then.then.then (F:\Git\ShadowMosesWebsite\src\ShadowMoses.Web\node_modules\@ngtools\webpack\src\plugin.js:495:24)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)
>

**Comment by Bidthedog** [comment] 2017-11-23 21:50
This seems to have something to do with AOT - it only happens when I build via angular-cli with `ng build --prod` or `ng build -aot`. Here's an article explaining how to set things up:

https://angular.io/guide/aot-compiler

**Comment by Bidthedog** [comment] 2017-11-23 22:12
Replication as follows:

- ng new test-proj
- npm i ng2-animate-on-scroll --save
- Update app.module.ts as follows:

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
 
import { AppComponent } from './app.component';
 
// import third-party module
import { AnimateOnScrollModule } from 'ng2-animate-on-scroll';
 
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
 
    // import module here
    AnimateOnScrollModule.forRoot()
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

- ng serve --prod

You'll see the error:

> webpack: Compiling...
> Date: 2017-11-23T22:11:25.812Z
> Hash: bebbb386eff28ce13487
> Time: 4768ms
> chunk {0} main.8863ea6104f3ce602132.bundle.js (main) 142 kB [initial]
> chunk {1} styles.d41d8cd98f00b204e980.bundle.css (styles) 0 bytes [initial]
> chunk {2} polyfills.15a5360536ec2fbcfea9.bundle.js (polyfills) 86 bytes [initial]
> chunk {3} inline.0fb909a010f23727eb14.bundle.js (inline) 1.45 kB [entry]
> 
> ERROR in Error: Error encountered resolving symbol values statically. Calling function 'AnimateOnScrollModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in D:/git/test-proj/src/app/app.module.ts, resolving symbol AppModule in D:/git/test-proj/src/app/app.module.ts
> 
> 
> webpack: Failed to compile.

**Comment by Bidthedog** [comment] 2017-11-26 15:03
Holding me back from publishing my new website now - any chance you'll get a chance to look at this? Not sure how to fix this myself, nothing is standing out and the error isn't really helpful.

**Comment by abhazelton** [comment] 2017-11-26 15:12
Sorry, man. Will try to look at it tonight.


Aaron Hazelton

**Comment by Bidthedog** [comment] 2017-11-26 15:53
Thanks dude - I've just made some progress, about to make a PR but I don't know how to test it.

Followed this article to publish metadata for angular cli:

https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad

Creating a PR now, up to you what you do with it! :)

**Comment by abhazelton** [comment] 2017-11-30 03:16
It appears from the error that its an issue with AoT, but I'm going off of this list of things to do with functions to avoid any errors and can't see where I'm violating one of those rules.  Paid work dictates getting back to other projects, so if anyone interested sees where the culprit might be, that is welcome.

Here's the page with the "Do's" and "Don'ts" for AoT:
https://github.com/rangle/angular-2-aot-sandbox

I'm still getting errors using the PR from @Bidthedog.

**Comment by Bidthedog** [comment] 2017-11-30 10:22
I'm going to do some further investigations when I can, but I also have paid work on at the mo, hah! I desperately need to launch my website, so this is a priority for me - outside of work at least.

**Comment by abhazelton** [comment] 2017-12-04 16:31
@Bidthedog I'm getting additional errors with the changes from the PR, regarding incorrect implementation of fromEvent.. are you not getting any errors?  I'm using npm link to use the local copy in a project, and still getting the compilation errors in the test project.

**Comment by Bidthedog** [comment] 2017-12-04 16:43
I was getting that error, but I rectified it by adding `import 'rxjs/add/observable/fromEvent';` to the top of scroll.service.ts. The latest AOT compiler is a bit fussier than the previous one when it comes to imports - you have to be very specific, apparently.

Apologies - I forgot about `npm link` - I don't work on npm packages very often and not had much spare time to refresh myself. I'll try linking my PR to my project this evening and see how I get on.

FYI I launched my site last week - ended up copying the module into my own project and getting it compiling in there :)

**Comment by inklingsofreality** [comment] 2017-12-08 18:23
Now getting this error on compile:
`ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'AnimateOnScrollModule' was called.`

**Comment by Bidthedog** [comment] 2017-12-11 08:23
I did spend a night trying to properly fix this up, but I wasn't getting anywhere fast, and I've been snowed under with much needed "real" work.

I *think* the solution to this might be to just roll a brand new angular-cli based / focused library and copy the implementation. Wouldn't mind adding tests too!

**Comment by inklingsofreality** [comment] 2017-12-11 14:31
I should add that this happens when I attempt a production build. However, running:
`ng build -prod -aot=false'
I do not get the error and it builds okay.

**Comment by mouf13** [comment] 2018-01-14 17:06
can you merge please ?

**Comment by sathwik77** [comment] 2018-02-10 07:29
I am still getting this error. I am on angular 4.4.6
`ERROR in Error: Error encountered resolving symbol values statically. Calling function 'AnimateOnScrollModule', function calls are not supported.`

**Comment by AaronLavers** [comment] 2018-04-11 03:52
Hey guys, just wondering if anyones gotten any further with a solution for this? The library seems pretty much unusable at the moment as on a docker compile it spits back the error 

> Function calls are not supported in decorators but 'AnimateOnScrollModule' was called.

**Comment by abhazelton** [comment] 2018-04-13 20:40
Hi everybody, sorry to have dropped off on this but haven't had time to focus on it and it wasn't a high priority (sorry).  I find through quite a bit of research online that there are a lot of people getting that error for a number of different reasons and no one seems to be able to provide a concrete answer as to the cause.  

I've tried changing a number of things some others suggest and still end up with the error.  I've decided to just rewrite it since I believe some of the functions will need to work differently anyways to be compatible with AOT compilation.  Hope to have it up within a couple weeks.

**Comment by inklingsofreality** [comment] 2018-05-31 16:10
Added the following in index.d.ts just before the 'export declare class' and the error went away

```
@NgModule ({

})
```

**Comment by inklingsofreality** [comment] 2018-05-31 20:19
After some testing, for a production build, I removed .forRoot() from the app.module.ts, but needed it for running locally. I also changed the @NgModule declaration to the following.

```
@NgModule ({
    providers: [
        AnimateOnScrollModule
    ] // making NgModules available to other parts of the app
})
```

**Comment by abhazelton** [comment] 2018-07-20 05:05
Working on an Angular 6 version currently, but for now going with the most recent PR.

**Closed** 2018-08-01 06:31 UTC
