### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by georgeMuraveiAlkh** [abhazelton/animate-on-scroll#11] opened 2017-12-03 01:49 UTC
Angular-cli: 1.5.5
ng2-animate-on-scroll: 1.0.7 - 1.0.8

Error while ng serve
`ERROR in Error: Error encountered resolving symbol values statically. Calling function 'AnimateOnScrollModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported
 function, resolving symbol AppModule in C:/Projects/foxbet-landing2/src/app/app.module.ts, resolving symbol AppModule in C:/Projects/foxbet-landing2/src/app/app.module.ts
    at syntaxError (C:\Projects\foxbet-landing2\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at simplifyInContext (C:\Projects\foxbet-landing2\node_modules\@angular\compiler\bundles\compiler.umd.js:25118:23)
    at StaticReflector.simplify (C:\Projects\foxbet-landing2\node_modules\@angular\compiler\bundles\compiler.umd.js:25130:13)
    at StaticReflector.annotations (C:\Projects\foxbet-landing2\node_modules\@angular\compiler\bundles\compiler.umd.js:24558:41)
    at _getNgModuleMetadata (C:\Projects\foxbet-landing2\node_modules\@angular\compiler-cli\src\ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (C:\Projects\foxbet-landing2\node_modules\@angular\compiler-cli\src\ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (C:\Projects\foxbet-landing2\node_modules\@angular\compiler-cli\src\ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (C:\Projects\foxbet-landing2\node_modules\@angular\compiler-cli\src\ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (C:\Projects\foxbet-landing2\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:241:66)
    at _donePromise.Promise.resolve.then.then.then.then.then (C:\Projects\foxbet-landing2\node_modules\@angular\cli\node_modules\@ngtools\webpack\src\plugin.js:495:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
`

**Comment by abhazelton** [comment] 2017-12-04 16:05
Duplicate of [#9](https://github.com/abhazelton/animate-on-scroll/issues/9).  We are working on this.

**Closed by abhazelton** 2017-12-04 16:05 UTC
